# Generated by Django 2.2.8 on 2020-06-15 04:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companys',
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(blank=True, choices=[('C', 'Cuantitativo'), ('Q', 'Cualitativo')], max_length=100)),
                ('unidad', models.CharField(blank=True, max_length=50)),
                ('desc', models.TextField()),
            ],
            options={
                'verbose_name': 'Metric',
                'verbose_name_plural': 'Metrics',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateField()),
                ('end', models.DateField()),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('editable', models.BooleanField(default=True)),
                ('num_value', models.FloatField(blank=True, null=True)),
                ('text_value', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reports.Company')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='reports.Metric')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_modificados', to=settings.AUTH_USER_MODEL)),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='reports.Company')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('unidad', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('tipo', models.CharField(choices=[('S', 'Simple'), ('R', 'Rango'), ('P', 'Porcentaje'), ('E', 'Especial')], max_length=2)),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='reports.Company')),
                ('metrics', models.ManyToManyField(related_name='indicators', to='reports.Metric')),
            ],
            options={
                'verbose_name': 'Indicator',
                'verbose_name_plural': 'Indicators',
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, max_length=50, null=True)),
                ('begin', models.DateField()),
                ('end', models.DateField()),
                ('goal', models.IntegerField()),
                ('fail', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.int_list_validator])),
                ('result', models.IntegerField(null=True)),
                ('completed', models.BooleanField(default=False)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='reports.Indicator')),
            ],
            options={
                'verbose_name': 'Goal',
                'verbose_name_plural': 'Goals',
            },
        ),
        migrations.CreateModel(
            name='Asignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodic', models.NullBooleanField(default=True)),
                ('last', models.DateField(blank=True)),
                ('deliver_time', models.IntegerField()),
                ('frecuency', models.CharField(choices=[('MONT', 'Mensual'), ('WEEK', 'Semanal'), ('DAY', 'Diario')], max_length=50)),
                ('metafreq', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.int_list_validator])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expected_reports', to='reports.Company')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Metric')),
            ],
            options={
                'verbose_name': 'Asignment',
                'verbose_name_plural': 'Asignments',
            },
        ),
    ]
