# Generated by Django 2.2.8 on 2020-09-16 21:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companys',
            },
        ),
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(blank=True, choices=[('A', 'Acumulativa'), ('E', 'Estado'), ('C', 'Constante'), ('COMP', 'Computada')], default='A', max_length=100)),
                ('unidad', models.CharField(blank=True, max_length=50)),
                ('desc', models.TextField()),
                ('formula_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('dependencies', models.ManyToManyField(related_name='_metric_dependencies_+', to='reports.Metric')),
            ],
            options={
                'verbose_name': 'Metric',
                'verbose_name_plural': 'Metrics',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateField()),
                ('end', models.DateField(blank=True, null=True)),
                ('constant', models.BooleanField(blank=True, default=False)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('editable', models.BooleanField(default=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reports.Company')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='reports.Metric')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_modificados', to=settings.AUTH_USER_MODEL)),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='reports.Company')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('unidad', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('tipo', models.CharField(choices=[('S', 'Simple'), ('E', 'Estado'), ('A', 'Acumulado'), ('C', 'Cociente'), ('P', 'Porcentaje'), ('SA', 'Producto')], default='A', max_length=2)),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='reports.Company')),
                ('metrics', models.ManyToManyField(related_name='indicators', through='reports.Components', to='reports.Metric')),
            ],
            options={
                'verbose_name': 'Indicator',
                'verbose_name_plural': 'Indicators',
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('group', models.CharField(blank=True, max_length=50, null=True)),
                ('begin', models.DateField()),
                ('end', models.DateField()),
                ('goal', models.IntegerField()),
                ('fail', models.CharField(blank=True, max_length=50, null=True)),
                ('reverse', models.BooleanField(default=False)),
                ('result', models.IntegerField(null=True)),
                ('completed', models.BooleanField(default=False)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='reports.Indicator')),
            ],
            options={
                'verbose_name': 'Goal',
                'verbose_name_plural': 'Goals',
            },
        ),
        migrations.AddField(
            model_name='components',
            name='indicator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='reports.Indicator'),
        ),
        migrations.AddField(
            model_name='components',
            name='metrica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.Metric'),
        ),
        migrations.AddField(
            model_name='company',
            name='metrics',
            field=models.ManyToManyField(to='reports.Metric'),
        ),
        migrations.CreateModel(
            name='Asignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodic', models.NullBooleanField(default=True)),
                ('last_begin', models.DateField(blank=True, default=django.utils.timezone.localdate)),
                ('last_end', models.DateField()),
                ('days_to_deliver', models.IntegerField()),
                ('frecuency', models.CharField(choices=[('MONT', 'Mensual'), ('WEEK', 'Semanal'), ('DAY', 'Diario'), ('OT', 'OneTime')], default='OT', max_length=50)),
                ('metafreq', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.int_list_validator])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expected_reports', to='reports.Company')),
                ('genetated_reports', models.ManyToManyField(related_name='asignment', to='reports.Report')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Metric')),
            ],
            options={
                'verbose_name': 'Asignment',
                'verbose_name_plural': 'Asignments',
            },
        ),
    ]
