# Generated by Django 2.2.8 on 2020-09-16 21:30

from django.db import migrations
from hubscope.reports.models import Metric, Indicator

INITIAL_METRICS=[
    {
        "name":'Aves Alojadas',
        "tipo":'E',
        "unidad":'Aves',
        "desc":'Suma de el ingreso de aves a producción, la salida de aves de producción y el número de aves muertas',

    },
    {
       "name":'Capacidad de Alojamiento Teórico',
        "tipo":'C',
        "unidad":'Espacio',
        "desc":'Capacidad de Alojamiento',
        "value":200,

    },
    {
       "name":'Cajas',
        "tipo":'A',
        "unidad":'Cajas',
        "desc":'Cajas de huevos producidas',
    },    
    {
       "name":'Aves Muertas',
        "tipo":'A',
        "unidad":'Aves',
        "desc":'Numero de aves muertas',
    },    
    {
        "name":'ABA servida',
        "tipo":'A',
        "unidad":'Kilogramos',
        "desc":'Kilogramos de ABA servidos',
    },
    {
        "name":'Consumo esperado',
        "tipo":'COMP',
        "desc":'Consumo esperado de las aves alojadas de acuerdo a la linea genetica (0.11)',
        "unidad":'Kilogramos de ABA',
        'formula_name':'consumo_esperado',
        'dependencies':[
            'Aves Alojadas'
        ]
    },

]

def apply_migration(apps, schema_editor):
    # User = apps.get_model('accounts', 'User')
    for metric_data in INITIAL_METRICS:
        dependencies = metric_data.pop('dependencies', [])
        new_metric = Metric.objects.create(**metric_data)
        for dep_name in dependencies:
            dependency=Metric.objects.get(name=dep_name)
            new_metric.dependencies.add(dependency)

def revert_migration(apps, schema_editor):
    metric_names = [m['name'] for m in INITIAL_METRICS]
    Metric.objects.filter(name__in=metric_names).delete()




class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(apply_migration, revert_migration)
    ]


# Generated by Django 2.2.4 on 2019-11-17 16:57

