# Generated by Django 2.2.8 on 2020-08-02 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_mock_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='reports.Indicator'),
        ),
    ]
