# Generated by Django 2.2.4 on 2019-11-17 16:57
from django.db import migrations
from django.contrib.auth.models import Group

GROUP_NAMES=[
    Group(name='Admin'),
    Group(name='Gerente'),
    Group(name='Registrador'),
    Group(name='Ejecutivo'),
]

def apply_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.bulk_create(GROUP_NAMES)

def revert_migration(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(
        name__in=[g.name for g in GROUP_NAMES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(apply_migration, revert_migration)
    ]
