# Generated by Django 2.2.4 on 2019-11-17 16:57
from django.db import migrations
from django.contrib.auth.models import Group
from hubscope.accounts.models import User

INITIAL_USERS=[
    {
        "email":'ogspain@gmail.com',
        "password":'18275998',
        "first_name":'Omar',
        "last_name":'España',
        "username":'ogespana',
        "is_staff":True,
        "is_superuser":True
    },
    {
        "email":'ogspain@gmail.com',
        "password":'secreto',
        "first_name":'Katherine',
        "last_name":'Blassendorff',
        "username":'katiblas',
        "is_staff":True,
        "is_superuser":True
    }
]

def apply_migration(apps, schema_editor):
    # User = apps.get_model('accounts', 'User')
    for newu in INITIAL_USERS:
        User.objects.create_user(**newu)

def revert_migration(apps, schema_editor):
    Group = apps.get_model('accounts', 'User')
    Group.objects.filter(
        username__in=[u['username'] for u in INITIAL_USERS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial_groups'),
    ]

    operations = [
        migrations.RunPython(apply_migration, revert_migration)
    ]
